### PR TITLE
my_each

### PR DESCRIPTION
**Pull request by frameq**
@nonkor need review

### CODE REVIEW

**Review by nonkor — APPROVED** [review]
Well done!
Add some samples and feel free to merge it.

**Comment by frameq** [comment]
I dont have rights:

```
DMartyshevskyi:Betlab-ruby-courses dmytro.martyshevskyi$ git merge homework_3
Merge made by the 'recursive' strategy.
 lesson3/hometask_frameq.rb | 26 ++++++++++++++++++++++++++
 1 file changed, 26 insertions(+)
 create mode 100644 lesson3/hometask_frameq.rb
DMartyshevskyi:Betlab-ruby-courses dmytro.martyshevskyi$ git push origin master
ERROR: Permission to nonkor/Betlab-ruby-courses.git denied to frameq.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by nonkor** [comment]
@frameq I guess your troubles with rights were gone. What's status here?

**Comment by frameq** [comment]
@nonkor job is done

**Pull request merged**
